scmmanager:
  image: fanday/scm-manager
  ports:
   - "8080:8080"
  links:
   - ldap

ldap:
  image: fanday/openldap
  ports:
   - "8081:80"
   
jenkins:
  image: jenkins
  ports:
   - "8082:8080"
     
sonarqube:
  image: sonarqube
  ports:
   - "9000:9000" 
   - "9092:9092"
  env_file:
   - ./common.env
  links:
   - mysql
   
mysql:
  image: mysql
  ports:
   - "3306:3306"
  env_file:
   - ./common.env
  
